### ISSUE TITLE
Add tip about git branch --set-upstream-to=origin/main with Git 2.29.0

### ISSUE THREAD

**Issue by damymetzke** [HonkingGoose/git-gosling#65]
**Is your feature request related to a problem? Please describe.**
The latest version as of writing (*2.29.0*) of git does not allow the use of:
```shell
git branch --set-upstream origin main
```
Git Gosling currently makes no mention of this in the section `Create your first GitHub repo`.

**Describe the solution you'd like**
Mention the newer syntax. In that context it should be:
```shell
git branch --set-upstream-to=origin/main
```
When creating new branches the `--track` option is used, although I have not tested this myself.

**Describe alternatives you've considered**

**Additional context**
Link to documentation: https://git-scm.com/docs/git-branch#Documentation/git-branch.txt---set-upstream-toltupstreamgt

**Comment by HonkingGoose** [comment]
Thanks for reporting this issue. :+1:

**Comment by HonkingGoose** [comment]
I'm not using `git branch --set-upstream origin main` in the guide, I'm using `git push --set-upstream` instead.
So I don't know if this is causing problems for anybody following the guide to the letter.

According to the [Git documentation for git push](https://git-scm.com/docs/git-push), `git push --set-upstream <branch_name>` is still valid syntax with Git *2.29*.

Can you try out the `git push --set-upstream` command on Git *2.29*?

**Comment by damymetzke** [comment]
Ah I see that is why I had trouble creating the branch on the remote.
I tested it and `git push --set-upstream` does indeed still work.
It's confusing though, since doing it through `git branch` makes just as much sense logically;
it even allows for the same options, but they only changed the way it works for `git branch`.

**Comment by HonkingGoose** [comment]
I will add this information as a tip somewhere.

**Comment by HonkingGoose** [comment]
I've tried the `git branch --set-upstream-to=` on a new branch, where there is no remote branch.
Git then hints you to do a `git push` anyways:

```git
$ git branch --set-upstream-to=origin/feature/65
error: the requested upstream branch 'origin/feature/65' does not exist
hint: 
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint: 
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.
```

For this reason I think it's better to only cover the `git push --set-upstream` command, as that pushes/creates the branch on the remote, and sets the remote branch in one go.

I'm marking this `wont-fix` for now, and closing this issue.

Feel free to re-open this if you find a good use-case for covering this command.
